// Generated by CoffeeScript 1.9.3
(function() {
  var Test;

  Test = (function() {
    var Page;

    Page = Util.Import('page/Page');

    Page.Test = Test;

    Util.Export(Page.Test, 'page/Page.Test');

    function Test(ui, trip, destinationUI, goUI, tripUI, navigateUI) {
      this.ui = ui;
      this.trip = trip;
      this.destinationUI = destinationUI;
      this.goUI = goUI;
      this.tripUI = tripUI;
      this.navigateUI = navigateUI;
      Util.log('Page.Test.constructor');
    }

    return Test;

  })();

}).call(this);
