// Generated by CoffeeScript 1.10.0
(function() {
  var $, AdvisoryUC, DriveBarUC, TripUI, WeatherUC;

  $ = require('jquery');

  WeatherUC = require('js/exit/uc/WeatherUC');

  AdvisoryUC = require('js/exit/uc/AdvisoryUC');

  DriveBarUC = require('js/exit/uc/DriveBarUC');

  TripUI = (function() {
    module.exports = TripUI;

    function TripUI(stream) {
      this.stream = stream;
      this.weatherUC = new WeatherUC(this.stream, 'Trip', [0, 0, 100, 54], [0, 0, 100, 50]);
      this.advisoryUC = new AdvisoryUC(this.stream, 'Trip', [0, 54, 100, 10], [0, 50, 100, 10]);
      this.driveBarUC = new DriveBarUC(this.stream, 'Trip', [4, 64, 92, 36], [4, 60, 92, 40]);
    }

    TripUI.prototype.ready = function() {
      this.weatherUC.ready();
      this.advisoryUC.ready();
      this.driveBarUC.ready();
      this.$ = $(this.html());
      return this.$.append(this.weatherUC.$, this.advisoryUC.$, this.driveBarUC.$);
    };

    TripUI.prototype.position = function(screen) {
      this.weatherUC.position(screen);
      this.advisoryUC.position(screen);
      this.driveBarUC.position(screen);
      return this.subscribe();
    };

    TripUI.prototype.subscribe = function() {
      return this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
    };

    TripUI.prototype.onScreen = function(screen) {
      return Util.noop('TripUI.onScreen()', screen);
    };

    TripUI.prototype.html = function() {
      return "<div id=\"" + (Util.htmlId('TripUI')) + "\" class=\"" + (Util.css('TripUI')) + "\"></div>";
    };

    TripUI.prototype.show = function() {
      return this.$.show();
    };

    TripUI.prototype.hide = function() {
      return this.$.hide();
    };

    return TripUI;

  })();

}).call(this);
