// Generated by CoffeeScript 1.6.3
(function() {
  var $, Navb, UI,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = require('jquery');

  UI = require('js/ui/UI');

  Navb = (function() {
    module.exports = Navb;

    function Navb(stream, navbSpecs) {
      this.stream = stream;
      this.signonForm = __bind(this.signonForm, this);
      this.searchForm = __bind(this.searchForm, this);
      this.signon = __bind(this.signon, this);
      this.search = __bind(this.search, this);
      this.specs = this.createSpecs(navbSpecs);
      this.htmlId = Util.getHtmlId('Navb', 'App');
    }

    Navb.prototype.createSpecs = function(navbSpecs) {
      var navbSpec, specs, _i, _len;
      specs = [];
      for (_i = 0, _len = navbSpecs.length; _i < _len; _i++) {
        navbSpec = navbSpecs[_i];
        specs.push(navbSpec);
      }
      return specs;
    };

    Navb.prototype.ready = function() {
      this.$navb = $('#' + this.htmlId);
      this.$navb.append(this.html());
      return this.publish();
    };

    Navb.prototype.id = function(spec, ext) {
      if (ext == null) {
        ext = '';
      }
      return Util.htmlId(spec.name, 'Navb', ext);
    };

    Navb.prototype.publish = function() {
      var eventType, item, spec, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.specs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        spec = _ref[_i];
        if (spec.htmlId != null) {
          spec.$ = $('#' + spec.htmlId);
          eventType = spec.subject === 'Submit' ? 'keyup' : 'click';
          if (spec.topic != null) {
            this.stream.publish(spec.subject, spec.topic, spec.$, eventType);
          }
        }
        if (spec.items != null) {
          _ref1 = spec.items;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            item = _ref1[_j];
            if (!(item.htmlId != null)) {
              continue;
            }
            item.$ = $('#' + item.htmlId);
            if (item.topic != null) {
              this.stream.publish(item.subject, item.topic, item.$, 'click');
            }
          }
        }
      }
    };

    Navb.prototype.getSpec = function(id) {
      var spec, _i, _len, _ref;
      _ref = this.specs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        spec = _ref[_i];
        if (spec.id === id) {
          return spec;
        }
      }
      Util.error('Navb.getSpec(id) spec null for id', id);
      return null;
    };

    Navb.prototype.html = function() {
      var htm, spec, _i, _len, _ref;
      htm = "<div class=\"navb\">";
      _ref = this.specs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        spec = _ref[_i];
        switch (spec.type) {
          case 'Brand':
            htm += "<a  class=\"navb-brand\" href=\"" + spec.href + "\">" + spec.name + "</a>";
            break;
          case 'NavBarLeft':
            htm += "<ul class=\"navb-ul-left\">";
            break;
          case 'NavBarRight':
            htm += "<ul class=\"navb-ul-right\">";
            break;
          case 'NavBarEnd':
            htm += "</ul>";
            break;
          case 'Item':
            htm += this.item(spec);
            break;
          case 'Link':
            htm += this.link(spec);
            break;
          case 'Dropdown':
            htm += this.dropdown(spec);
            break;
          case 'FileInput':
            htm += this.fileInput(spec);
            break;
          case 'Image':
            htm += this.image(spec);
            break;
          case 'Search':
            htm += this.search(spec);
            break;
          case 'Contact':
            htm += this.contact(spec);
            break;
          case 'SignOn':
            htm += this.signon(spec);
            break;
          default:
            Util.error('UI.Navb unknown spec type', spec.type);
        }
      }
      htm += "</div>";
      return htm;
    };

    Navb.prototype.show = function() {
      this.$navb.show();
    };

    Navb.prototype.hide = function() {
      this.$navb.hide();
    };

    Navb.prototype.item = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li id=\"" + spec.htmlId + "\" class=\"navb-item\"><i class=\"fa " + spec.icon + " fa-lg\"></i> " + spec.name + "</li>";
    };

    Navb.prototype.link = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li class=\"navb-link\"><a id=\"" + spec.htmlId + "\"><i title=\"" + spec.name + "\" class=\"fa " + spec.icon + " fa-lg\"></i> " + spec.name + "</a></li>";
    };

    Navb.prototype.dropdown = function(spec) {
      var htm, item, _i, _len, _ref;
      htm = "<li class=\"navb-drop\">";
      htm += "<i class=\"fa " + spec.icon + " fa-lg\"/> " + spec.name + "  <i class=\"fa fa-caret-down\"/>";
      htm += "<ul>";
      _ref = spec.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        item.htmlId = this.id(item, spec.name);
        htm += "<li id=\"" + item.htmlId + "\">" + item.name + "</li>";
      }
      htm += "</ul></li>";
      return htm;
    };

    Navb.prototype.image = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li id=\"" + spec.htmlId + "\" class=\"navb-image-li\"><i class=\"fa " + spec.icon + "\"/>&nbsp;Image</li>";
    };

    Navb.prototype.fileInput = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li class=\"navb-fileinput-li\"><input id=\"" + spec.htmlId + "\" class=\"navb-fileinput\" placeholder=\"  &#xF0F6; Input File\"  type=\"file\" size=\"" + spec.size + "\"></li>";
    };

    Navb.prototype.search = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li class=\"navb-search-li\"><input id=\"" + spec.htmlId + "\" class=\"navb-search\" placeholder=\"  &#xF002; Search\"  type=\"text\" size=\"" + spec.size + "\"></li>";
    };

    Navb.prototype.signon = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li class=\"navb-signon-li\"><input id=\"" + spec.htmlId + "\" class=\"navb-signon\" placeholder=\"  &#xF090; Sign On\" type=\"text\" size=\"" + spec.size + "\"></li>";
    };

    Navb.prototype.searchForm = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li><form id=\"" + spec.htmlId + "\" name=\"search\" class=\"navb-search\">\n<input name=\"criteria\" placeholder=\"  &#xF002;  " + spec.name + "\" type=\"text\" size=\"" + spec.size + "\")\">\n<label for=\"SEARCH\"></label></form></li>";
    };

    Navb.prototype.signonForm = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li><form id=\"" + spec.htmlId + "\" name=\"login\" class=\"navb-signon\">\n<input name=\"user\" placeholder=\"  &#xF090;  Sign On\" type=\"text\" size=\"" + spec.size + "\">\n<label for=\"SIGNON\"></label></form></li>";
    };

    Navb.prototype.contact = function(spec) {
      spec.htmlId = this.id(spec);
      return "<li class=\"navb-contact\"><a id=\"" + spec.htmlId + "\"><i class=\"fa " + spec.icon + " fa-lg\"></i> " + spec.name + "</a></li>";
    };

    return Navb;

  })();

}).call(this);
