// Generated by CoffeeScript 1.10.0
(function() {
  var Stream, Test, UI;

  window.xUtil.fixTestGlobals();

  Stream = require('js/util/Stream');

  UI = require('js/ui/UI');

  beforeAll(function() {
    var stream;
    stream = new Stream();
    return Util.noop(stream);
  });

  Test = (function() {
    function Test() {}

    return Test;

  })();

  describe("ui/UI.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/Btn.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/Group.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/Navb.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/Pane.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/Part.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/Stream.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/Tocs.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ui/View.coffee", function() {
    return it("constructor", function() {
      return expect(true).toBe(true);
    });
  });

}).call(this);
