// Generated by CoffeeScript 1.10.0
(function() {
  var $, BannerUC;

  $ = require('jquery');

  BannerUC = (function() {
    module.exports = BannerUC;

    function BannerUC(stream, role, port, land) {
      this.stream = stream;
      this.role = role;
      this.port = port;
      this.land = land;
      this.screen = {};
      this.recommendation = '?';
    }

    BannerUC.prototype.ready = function() {
      this.$ = $(this.html());
      return this.$bannerText = this.$.find('#BannerText');
    };

    BannerUC.prototype.position = function(screen) {
      this.onScreen(screen);
      return this.subscribe();
    };

    BannerUC.prototype.subscribe = function() {
      this.stream.subscribe('Location', (function(_this) {
        return function(location) {
          return _this.onLocation(location);
        };
      })(this));
      this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
      return this.stream.subscribe('Trip', (function(_this) {
        return function(trip) {
          return _this.onTrip(trip);
        };
      })(this));
    };

    BannerUC.prototype.onLocation = function(location) {
      return Util.noop('BannerUC.onLocation()', this.ext, location);
    };

    BannerUC.prototype.onTrip = function(trip) {
      return this.changeRecommendation(trip.recommendation);
    };

    BannerUC.prototype.changeRecommendation = function(recommendation) {
      var klass;
      this.recommendation = recommendation;
      klass = recommendation === 'GO' ? 'GoBanner' : 'NoGoBanner';
      this.$.attr('class', klass);
      return this.resetText();
    };

    BannerUC.prototype.resetText = function() {
      var html;
      html = this.recommendation === 'NO GO' && this.screen.orientation === 'Landscape' ? 'NO<br/>GO' : this.recommendation;
      return this.$bannerText.html(html);
    };

    BannerUC.prototype.onScreen = function(screen) {
      this.screen = screen;
      Util.cssPosition(this.$, screen, this.port, this.land);
      return this.resetText();
    };

    BannerUC.prototype.html = function() {
      return "<div   id=\"" + (Util.htmlId('BannerUC')) + "\"   class=\"" + (Util.css('GoBannerUC')) + "\">\n  <div id=\"" + (Util.htmlId('BannerText')) + "\" class=\"" + (Util.css('BannerText')) + "\">GO</div>\n</div>";
    };

    return BannerUC;

  })();

}).call(this);
