// Generated by CoffeeScript 1.10.0
(function() {
  var $, ThresholdUC;

  $ = require('jquery');

  ThresholdUC = (function() {
    module.exports = ThresholdUC;

    function ThresholdUC(stream, ext, port, land) {
      this.stream = stream;
      this.ext = ext;
      this.port = port;
      this.land = land;
    }

    ThresholdUC.prototype.ready = function() {
      return this.$ = $(this.html());
    };

    ThresholdUC.prototype.position = function(screen) {
      this.onScreen(screen);
      return this.subscribe();
    };

    ThresholdUC.prototype.subscribe = function() {
      return this.stream.subscribe('Screen', (function(_this) {
        return function(screen) {
          return _this.onScreen(screen);
        };
      })(this));
    };

    ThresholdUC.prototype.onScreen = function(screen) {
      return Util.cssPosition(this.$, screen, this.port, this.land);
    };

    ThresholdUC.prototype.html = function() {
      return "<div id=\"" + (Util.htmlId('Threshold')) + "\"       class=\"" + (Util.css('Threshold')) + "\">\n   <div id=\"" + (Util.htmlId('ThresholdAdjust')) + "\" class=\"" + (Util.css('ThresholdAdjust')) + "\">Adjust Threshold</div>\n   <img src=\"" + Util.root + "img/exit/Threshold.png\" width=\"300\" height=\"200\">\n</div>";
    };

    ThresholdUC.prototype.show = function() {
      return this.$.show();
    };

    ThresholdUC.prototype.hide = function() {
      return this.$.hide();
    };

    return ThresholdUC;

  })();

}).call(this);
