// Generated by CoffeeScript 1.11.0
(function() {
  var Connect, Vis;

  Vis = require('js/util/Vis');

  Connect = (function() {
    var Prac;

    module.exports = Connect;

    Prac = require('js/prac/Prac');

    Prac.Connect = Connect;

    Connect.id = 0;

    Connect.msgs = [];

    Connect.migrateComplete = false;

    Connect.StatusEnum = ['Beg', 'In', 'End'];

    Connect.MsgTypeEnum = ['Convey', 'Flow', 'Conduit'];

    Connect.DirEnum = ['West', 'East', 'North', 'South', 'Prev', 'Next'];

    function Connect(ui, stream1, view, page, practice) {
      this.ui = ui;
      this.stream = stream1;
      this.view = view;
      this.page = page;
      this.practice = practice;
      this.name = this.practice.name;
      this.msgs = {};
    }

    Connect.prototype.ready = function() {
      var ref;
      ref = this.adjacentConnects(), this.west = ref[0], this.east = ref[1], this.north = ref[2], this.south = ref[3], this.prev = ref[4], this.next = ref[5];
      this.subscribe();
    };

    Connect.prototype.subscribe = function() {
      this.stream.subscribe('Select', (function(_this) {
        return function(select) {
          return _this.onSelect(select);
        };
      })(this));
      this.stream.subscribe('Content', (function(_this) {
        return function(content) {
          return _this.onContent(content);
        };
      })(this));
      this.stream.subscribe('Connect', (function(_this) {
        return function(msg) {
          return _this.onConnect(msg);
        };
      })(this));
      return this.stream.subscribe('Test', (function(_this) {
        return function(topic) {
          return _this.onTest(topic);
        };
      })(this));
    };

    Connect.prototype.adjacentConnects = function() {
      var connect, connects, dir, i, len, pane, prac, ref;
      connects = [];
      if (this.practice.column == null) {
        return connects;
      }
      ref = ['east', 'west', 'north', 'south'];
      for (i = 0, len = ref.length; i < len; i++) {
        dir = ref[i];
        prac = this.practice[dir];
        pane = prac.name !== 'None' ? this.view.getPaneOrGroup(prac.name, false) : this.view.emptyPane;
        connect = pane.name !== 'Empty' && (pane.page != null) ? pane.page.connect : {
          name: 'None'
        };
        connects.push(connect);
      }
      return connects;
    };

    Connect.prototype.onSelect = function(select) {
      if (select.name !== this.name) {
        return;
      }
    };

    Connect.prototype.onContent = function(content) {
      if (content.content !== 'Connect' || content.practice !== this.name) {
        return;
      }
    };

    Connect.prototype.onTest = function(topic) {
      switch (topic) {
        case 'Populate':
          this.stream.publish('Content', {
            content: "Connect",
            name: "All"
          });
          Connect.testPopulate(this.stream);
          break;
        case 'Migrate':
          this.stream.publish('Content', {
            content: "Connect",
            name: "All"
          });
          Connect.testMigrate(this.ui.build);
      }
    };

    Connect.prototype.onConnect = function(msg) {
      if (!this.isSrc(msg) || !this.isMsg(msg)) {
        return;
      }
      msg.dir = this.dir(msg);
      switch (msg.type) {
        case 'Convey':
          this.onConvey(msg);
          break;
        case 'Flow':
          this.onFlow(msg);
          break;
        case 'Conduit':
          this.onConduit(msg);
          break;
        default:
          Util.error('Prac.Connect.onConnect() unknown msg type', msg.type);
      }
      if (msg.status !== 'Beg') {
        Util.error('Prac.Connect.onConnect() msg not processed', msg.name, msg.id);
      }
    };

    Connect.prototype.onConvey = function(convey) {
      if (!this.isConvey(convey)) {
        return;
      }
      if (convey.src === 'To' + this.name) {
        this.onItem(convey, convey.dir);
      } else if (convey.src === this.west.name) {
        this.onItem(convey, 'West');
      } else if (convey.src === this.east.name) {
        this.onItem(convey, 'East');
      }
      this.msgs[convey.id] = convey;
      return convey.status = 'Beg';
    };

    Connect.prototype.onFlow = function(flow) {
      if (!this.isFlow(flow)) {
        return;
      }
      if (flow.src === 'To' + this.name) {
        this.onItem(flow, flow.dir);
      } else if (flow.src === this.north.name) {
        this.onItem(flow, 'North');
      } else if (flow.src === this.south.name) {
        this.onItem(flow, 'South');
      }
      this.msgs[flow.id] = flow;
      return flow.status = 'Beg';
    };

    Connect.prototype.onConduit = function(conduit) {
      if (!this.isConduit(conduit)) {
        return;
      }
      if (conduit.src === 'To' + this.name) {
        this.onItem(conduit, conduit.dir);
      } else if (conduit.src === this.prev.name) {
        this.onItem(conduit, 'Prev');
      } else if (conduit.src === this.next.name) {
        this.onItem(conduit, 'Next');
      }
      this.msgs[conduit.id] = conduit;
      return conduit.status = 'Beg';
    };

    Connect.prototype.toWest = function(id) {
      return this.migrate(id, 'West');
    };

    Connect.prototype.toEast = function(id) {
      return this.migrate(id, 'East');
    };

    Connect.prototype.toNorth = function(id) {
      return this.migrate(id, 'North');
    };

    Connect.prototype.toSouth = function(id) {
      return this.migrate(id, 'South');
    };

    Connect.prototype.toPrev = function(id) {
      return this.migrate(id, 'Prev');
    };

    Connect.prototype.toNext = function(id) {
      return this.migrate(id, 'Next');
    };

    Connect.prototype.migrate = function(id, dir) {
      var msg;
      if (!this.canMigrate(id, dir)) {
        return;
      }
      msg = this.msgs[id];
      this.rmItem(msg);
      msg.dir = dir;
      msg.src = this.name;
      this.connect(dir).onConnect(msg);
      return delete this.msgs[msg.id];
    };

    Connect.prototype.canMigrate = function(id, dir) {
      var msg;
      msg = this.msgs[id];
      return (msg != null) && this.dirOk(msg, dir) && this.isConnected(dir);
    };

    Connect.prototype.onItem = function(msg, dir) {
      var elem$, htmlId;
      htmlId = this.page.contents.connect.htmlId + dir;
      elem$ = this.page.contents.connect.$.find('#' + htmlId);
      elem$.append("<li id=\"" + (htmlId + msg.id) + "\">" + msg.name + "</li>");
      msg.dir = dir;
    };

    Connect.prototype.rmItem = function(msg) {
      var $, htmlId;
      htmlId = this.page.contents.connect.htmlId + msg.dir + msg.id;
      $ = this.page.contents.connect.$.find('#' + htmlId);
      $.remove();
    };

    Connect.prototype.dir = function(msg) {
      var dir;
      dir = msg.dir;
      if (msg.src.substring(0, 2) === 'To') {
        switch (this.practice.column) {
          case 'Embrace':
            dir = 'West';
            break;
          case 'Encourage':
            dir = 'East';
            break;
          case 'Innovate':
            switch (this.practice.row) {
              case 'Learn':
                dir = 'North';
                break;
              case 'Do':
                dir = 'Next';
                break;
              case 'Share':
                dir = 'South';
                break;
              default:
                dir = msg.dir;
            }
            break;
          default:
            dir = msg.dir;
        }
      }
      return dir;
    };

    Connect.prototype.isSrc = function(msg) {
      if ((msg == null) || (msg.src == null) || (msg.type == null)) {
        return false;
      }
      if (msg.src === 'To' + this.name) {
        return true;
      }
      switch (msg.type) {
        case 'Convey':
          return msg.src === this.west.name || msg.src === this.east.name;
        case 'Flow':
          return msg.src === this.north.name || msg.src === this.south.name;
        case 'Conduit':
          return msg.src === this.prev.name || msg.src === this.next.name;
        default:
          return false;
      }
    };

    Connect.prototype.isMsg = function(msg) {
      var ok;
      ok = (msg != null) && (msg.id != null) && (msg.name != null) && this.isType(msg.type) && this.isDir(msg.dir) && this.isStatus(msg.status);
      if (msg == null) {
        Util.error('Prac.Connect.isMsg()', 'msg      null');
      }
      if ((msg != null) && (msg.id == null)) {
        Util.error('Prac.Connect.isMsg()', 'msg.id   null');
      }
      if ((msg != null) && (msg.name == null)) {
        Util.error('Prac.Connect.isMsg()', 'msg.name null');
      }
      return ok;
    };

    Connect.prototype.isConvey = function(convey) {
      return convey.type === 'Convey' && (this.msgs[convey.id] == null);
    };

    Connect.prototype.isFlow = function(flow) {
      return flow.type === 'Flow' && (this.msgs[flow.id] == null);
    };

    Connect.prototype.isConduit = function(conduit) {
      return conduit.type === 'Conduit' && (this.msgs[conduit.id] == null);
    };

    Connect.prototype.isType = function(type) {
      var ok;
      ok = Util.contains(Connect.MsgTypeEnum, type);
      if (!ok) {
        Util.error("Prac.Connect.isType() enum " + type + " not", Connect.MsgTypeEnum);
      }
      return ok;
    };

    Connect.prototype.isDir = function(dir) {
      var ok;
      ok = Util.contains(Connect.DirEnum, dir);
      if (!ok) {
        Util.error("Prac.Connect.isDir() enum " + dir + " not", Connect.DirEnum);
      }
      return ok;
    };

    Connect.prototype.isStatus = function(status) {
      var ok;
      ok = Util.contains(Connect.StatusEnum, status);
      if (!ok) {
        Util.error("Prac.Connect.isStatus() enum " + status + " not", Connect.StatusEnum);
      }
      return ok;
    };

    Connect.prototype.isConnected = function(dir) {
      return this.connect(dir).name !== 'None';
    };

    Connect.prototype.dirOk = function(msg, dir) {
      switch (dir) {
        case 'West':
        case 'East':
          return msg.type === 'Convey';
        case 'North':
        case 'South':
          return msg.type === 'Flow';
        case 'Prev':
        case 'Next':
          return msg.type === 'Conduit';
        default:
          return false;
      }
    };

    Connect.prototype.connect = function(dir) {
      switch (dir) {
        case 'West':
          return this.west;
        case 'East':
          return this.east;
        case 'North':
          return this.north;
        case 'South':
          return this.south;
        case 'Prev':
          return this.prev;
        case 'Next':
          return this.next;
        default:
          Util.error('Prac.Connect.toConnect() unknown direction', dir);
          return this.west;
      }
    };

    Connect.msg = function(id, name, type, src, status) {
      var dir, msg;
      if (status == null) {
        status = 'Beg';
      }
      dir = 'West';
      msg = {
        id: id,
        name: name,
        type: type,
        src: src,
        dir: dir,
        status: status
      };
      Connect.msgs.push(msg);
      return msg;
    };

    Connect.testPopulate = function(stream) {
      var msg1, msg2, msg3, msg4, msg5, msg6, msg7, msg8, msg9;
      msg1 = Connect.msg(1, 'Person', 'Convey', 'ToCollaborate');
      stream.publish('Connect', msg1);
      msg2 = Connect.msg(2, 'Entitle', 'Flow', 'ToConcept');
      stream.publish('Connect', msg2);
      msg3 = Connect.msg(3, 'Channel', 'Convey', 'ToDiscover');
      stream.publish('Connect', msg3);
      msg4 = Connect.msg(4, 'Trace', 'Convey', 'ToAdapt');
      stream.publish('Connect', msg4);
      msg5 = Connect.msg(5, 'Screen', 'Flow', 'ToTechnology');
      stream.publish('Connect', msg5);
      msg6 = Connect.msg(6, 'Review', 'Convey', 'ToBenefit');
      stream.publish('Connect', msg6);
      msg7 = Connect.msg(7, 'Config', 'Convey', 'ToChange');
      stream.publish('Connect', msg7);
      msg8 = Connect.msg(8, 'Support', 'Flow', 'ToFacilitate');
      stream.publish('Connect', msg8);
      msg9 = Connect.msg(9, 'Comply', 'Convey', 'ToGovern');
      return stream.publish('Connect', msg9);
    };

    Connect.testMigrate = function(build) {
      if (Connect.migrateComplete) {
        return;
      }
      build.migrateConnectMsg(1, 'East');
      build.migrateConnectMsg(2, 'South');
      build.migrateConnectMsg(3, 'West');
      build.migrateConnectMsg(4, 'East');
      build.migrateConnectMsg(6, 'West');
      build.migrateConnectMsg(7, 'East');
      build.migrateConnectMsg(8, 'North');
      build.migrateConnectMsg(9, 'West');
      return Connect.migrateComplete = true;
    };

    return Connect;

  })();

}).call(this);
