// Generated by CoffeeScript 1.12.2
(function() {
  var Menus;

  Menus = (function() {
    module.exports = Menus;

    function Menus(app, process, action) {
      this.app = app;
      this.process = process;
      this.action = action;
      this.name = 'Muse';
    }

    Menus.prototype.menus = function() {
      var all;
      all = [];
      if (this.process.platform === 'darwin') {
        all.push(this.macs());
      }
      all.push(this.file());
      all.push(this.edit());
      all.push(this.view());
      return all;
    };

    Menus.prototype.macs = function() {
      return {
        label: this.name,
        submenu: [
          {
            label: 'About ' + this.name,
            role: 'about'
          }, {
            type: 'separator'
          }, {
            label: 'Services',
            role: 'services',
            submenu: []
          }, {
            type: 'separator'
          }, {
            label: 'Hide ' + this.name,
            role: 'hide',
            accelerator: 'Command+H'
          }, {
            label: 'Hide Others',
            role: 'hideothers',
            accelerator: 'Command+Shift+H'
          }, {
            label: 'Show All',
            role: 'unhide'
          }, {
            label: 'Quit',
            accelerator: 'Command+Q',
            click: (function(_this) {
              return function() {
                return _this.app.quit();
              };
            })(this)
          }
        ]
      };
    };

    Menus.prototype.file = function() {
      return {
        label: 'File',
        submenu: [
          {
            label: 'New',
            accelerator: 'Command+N',
            click: (function(_this) {
              return function() {
                return _this.action.newf();
              };
            })(this)
          }, {
            label: 'Open',
            accelerator: 'Command+O',
            click: (function(_this) {
              return function() {
                return _this.action.open();
              };
            })(this)
          }, {
            label: 'Save',
            accelerator: 'Command+S',
            click: (function(_this) {
              return function() {
                return _this.action.save();
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Preferences',
            accelerator: 'Command+P',
            click: (function(_this) {
              return function() {
                return _this.action.pref();
              };
            })(this)
          }
        ]
      };
    };

    Menus.prototype.edit = function() {
      return {
        label: 'Edit',
        submenu: [
          {
            label: 'Undo',
            accelerator: 'Command+Z',
            click: (function(_this) {
              return function() {
                return _this.action.undo();
              };
            })(this)
          }, {
            label: 'Redo',
            accelerator: 'Command+U',
            click: (function(_this) {
              return function() {
                return _this.action.redo();
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Cut',
            accelerator: 'Command+X',
            click: (function(_this) {
              return function() {
                return _this.action.cut();
              };
            })(this)
          }, {
            label: 'Copy',
            accelerator: 'Command+C',
            click: (function(_this) {
              return function() {
                return _this.action.copy();
              };
            })(this)
          }, {
            label: 'Paste',
            accelerator: 'Command+V',
            click: (function(_this) {
              return function() {
                return _this.action.paste();
              };
            })(this)
          }, {
            label: 'Select All',
            accelerator: 'Command+A',
            click: (function(_this) {
              return function() {
                return _this.action.selectAll();
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Find',
            accelerator: 'Command+F',
            click: (function(_this) {
              return function() {
                return _this.action.find();
              };
            })(this)
          }, {
            label: 'Replace',
            accelerator: 'Command+R',
            click: (function(_this) {
              return function() {
                return _this.action.replace();
              };
            })(this)
          }
        ]
      };
    };

    Menus.prototype.view = function() {
      return {
        label: 'View',
        submenu: [
          {
            label: 'Close',
            accelerator: 'Command+W',
            click: (function(_this) {
              return function() {
                return _this.action.close();
              };
            })(this)
          }, {
            label: 'Skyline',
            click: (function(_this) {
              return function() {
                return _this.action.view('Skyline', '/htm/skyline/skyline.html');
              };
            })(this)
          }, {
            label: 'Test',
            click: (function(_this) {
              return function() {
                return _this.action.view('Test', '/htm/muse/Test.html');
              };
            })(this)
          }, {
            label: 'Store',
            click: (function(_this) {
              return function() {
                return _this.action.view('PouchDB', '/htm/muse/Store.html');
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Info',
            click: (function(_this) {
              return function() {
                return _this.action.view('Muse', '/htm/muse/Muse.html#Info');
              };
            })(this)
          }, {
            label: 'Augm',
            click: (function(_this) {
              return function() {
                return _this.action.view('Augm', '/htm/muse/Muse.html#Augm');
              };
            })(this)
          }, {
            label: 'Data',
            click: (function(_this) {
              return function() {
                return _this.action.view('Data', '/htm/muse/Muse.html#Data');
              };
            })(this)
          }, {
            label: 'Know',
            click: (function(_this) {
              return function() {
                return _this.action.view('Know', '/htm/muse/Muse.html#Know');
              };
            })(this)
          }, {
            label: 'Wise',
            click: (function(_this) {
              return function() {
                return _this.action.view('Wise', '/htm/muse/Muse.html#Wise');
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Exit',
            click: (function(_this) {
              return function() {
                return _this.action.view('Exit', '/htm/exit/Exit.html');
              };
            })(this)
          }, {
            label: 'Pivot',
            click: (function(_this) {
              return function() {
                return _this.action.view('Pivot', '/htm/pivot/Pivot.html');
              };
            })(this)
          }, {
            label: 'Hues',
            click: (function(_this) {
              return function() {
                return _this.action.view('Hues', '/htm/muse/Muse.html#Hues');
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'MuseTalk',
            click: (function(_this) {
              return function() {
                return _this.action.view('MuseTalk', '/htm/ikws/Muse.html');
              };
            })(this)
          }, {
            label: 'InfoTalk',
            click: (function(_this) {
              return function() {
                return _this.action.view('InfoTalk', '/htm/ikws/Info.html');
              };
            })(this)
          }, {
            label: 'DataTalk',
            click: (function(_this) {
              return function() {
                return _this.action.view('DataTalk', '/htm/ikws/Data.html');
              };
            })(this)
          }, {
            label: 'KnowTalk',
            click: (function(_this) {
              return function() {
                return _this.action.view('KnowTalk', '/htm/ikws/Know.html');
              };
            })(this)
          }, {
            label: 'WiseTalk',
            click: (function(_this) {
              return function() {
                return _this.action.view('WiseTalk', '/htm/ikws/Wise.html');
              };
            })(this)
          }, {
            label: 'EafdTalk',
            click: (function(_this) {
              return function() {
                return _this.action.view('EafdTalk', '/htm/ikws/Eafd.html');
              };
            })(this)
          }, {
            label: 'KnowScala',
            click: (function(_this) {
              return function() {
                return _this.action.view('KnowScala', '/htm/ikws/KnowScala.html');
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Color',
            click: (function(_this) {
              return function() {
                return _this.action.view('Color', '/htm/box/Box.html#Color');
              };
            })(this)
          }, {
            label: 'Cart',
            click: (function(_this) {
              return function() {
                return _this.action.view('Cart', '/htm/box/Box.html#Cart');
              };
            })(this)
          }, {
            label: 'Rgbs',
            click: (function(_this) {
              return function() {
                return _this.action.view('Rgbs', '/htm/box/Box.html#Rgbs');
              };
            })(this)
          }, {
            label: 'IKW',
            click: (function(_this) {
              return function() {
                return _this.action.view('IKW', '/htm/box/Box.html#IKW');
              };
            })(this)
          }, {
            label: 'Planes',
            click: (function(_this) {
              return function() {
                return _this.action.view('Planes', '/htm/box/Box.html#Planes');
              };
            })(this)
          }, {
            label: 'Sphere',
            click: (function(_this) {
              return function() {
                return _this.action.view('Sphere', '/htm/box/Box.html#Sphere');
              };
            })(this)
          }, {
            label: 'Regress',
            click: (function(_this) {
              return function() {
                return _this.action.view('Regress', '/htm/box/Box.html#Regress');
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Vecs',
            click: (function(_this) {
              return function() {
                return _this.action.view('Vecs', '/htm/box/Box.html#Vecs');
              };
            })(this)
          }, {
            label: 'VecRgb',
            click: (function(_this) {
              return function() {
                return _this.action.view('VecRgb', '/htm/box/Box.html#VecsRgb');
              };
            })(this)
          }, {
            label: 'VecHsv',
            click: (function(_this) {
              return function() {
                return _this.action.view('VecHsv', '/htm/box/Box.html#VecsHsv');
              };
            })(this)
          }, {
            label: 'PolarRgb',
            click: (function(_this) {
              return function() {
                return _this.action.view('PolarRgb', '/htm/box/Box.html#PolarRgb');
              };
            })(this)
          }, {
            label: 'ScaleRgb',
            click: (function(_this) {
              return function() {
                return _this.action.view('ScaleRgb', '/htm/box/Box.html#ScaleRgb');
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Plotly',
            click: (function(_this) {
              return function() {
                return _this.action.view('Plotly', '/htm/plot/Plot.html');
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Toggle Dev Tools',
            accelerator: 'Command+T',
            click: (function(_this) {
              return function() {
                return _this.action.toggleDevTools();
              };
            })(this)
          }
        ]
      };
    };

    return Menus;

  })();

}).call(this);
