// Generated by CoffeeScript 1.10.0
(function() {
  var C3V, Visual, c3, d3;

  Visual = require('js/visual/Visual');

  d3 = require('d3');

  c3 = require('c3');

  C3V = (function() {
    module.exports = C3Q;

    function C3V(stream) {
      this.stream = stream;
    }

    C3V.prototype.chart = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.data = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.axis = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.grid = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.region = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.legend = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.tooltip = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.subchart = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.zoom = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.point = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.line = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.area = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.bar = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.pie = function(obj) {
      return Util.noop(obj);
    };

    C3V.prototype.guage = function(obj) {
      return Util.noop(obj);
    };

    return C3V;

  })();

}).call(this);
