// Generated by CoffeeScript 1.11.0
(function() {
  var D3V, Visual, d3;

  Visual = require('js/visual/Visual');

  d3 = require('d3');

  D3V = (function() {
    module.exports = D3V;

    function D3V(stream) {
      this.stream = stream;
    }

    return D3V;

  })();

}).call(this);
