// Generated by CoffeeScript 1.10.0
(function() {
  var MathBoxV, Visual;

  Visual = require('js/visual/Visual');

  MathBoxV = (function() {
    module.exports = MathBoxV;

    function MathBoxV(stream) {
      this.stream = stream;
    }

    MathBoxV.prototype.inputData = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.outputData = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayCartesian = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayCylindrical = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displaySpherical = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayScatter = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayCurves = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayCurveFits = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displaySurfaces = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displaySurfaceFits = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayShapes = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayVectors = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displayQuanterions = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.displaySolar = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.mboxMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.coordMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.colorMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.museMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.namesMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.ncsMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.regressMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.cameraMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.platMBox = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.axis = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.face = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.grid = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.line = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.point = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.strip = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.surface = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.ticks = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.vector = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.view = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.cartesian = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.cartesian4 = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.polar = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.spherical = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.stereographic = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.stereographic4 = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.transform = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.transform4 = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.vertex = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.fragment = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.layer = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.mask = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.array = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.interval = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.matrix = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.area = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.voxel = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.volume = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.scale = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.html = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.dom = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.text = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.format = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.retext = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.label = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.clamp = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.grow = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.join = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.lerp = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.memo = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.readback = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.resample = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.repeat = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.swizzle = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.spread = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.split = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.slice = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.subdivide = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.transpose = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.group = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.inherit = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.root = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.unit = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.shader = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.camera = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.rtt = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.compose = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.clock = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.now = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.move = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.play = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.present = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.reveal = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.slide = function(obj) {
      return Util.noop(obj);
    };

    MathBoxV.prototype.step = function(obj) {
      return Util.noop(obj);
    };

    return MathBoxV;

  })();

}).call(this);
