// Generated by CoffeeScript 1.10.0
(function() {
  var Reactor, Visual;

  Visual = require('js/visual/Visual');

  Reactor = (function() {
    module.exports = Reactor;

    Visual.Reactor = Reactor;

    function Reactor(stream) {
      this.stream = stream;
    }

    return Reactor;

  })();

}).call(this);
