// Generated by CoffeeScript 1.10.0
(function() {
  var $, imgSrc, initialize, pdfCSS;

  $ = require('jquery');

  $(document).ready(function() {
    initialize();
    pdfCSS();
  });

  initialize = function() {
    var initHighFn, nodejs, preCodeFn, revdir;
    nodejs = '../../node_modules/';
    revdir = nodejs + 'reveal.js/';
    preCodeFn = function() {
      return !!document.querySelector('pre code');
    };
    initHighFn = function() {
      return hljs.initHighlightingOnLoad();
    };
    Reveal.initialize({
      controls: true,
      progress: true,
      history: true,
      center: true,
      slideNumber: true,
      transition: 'slide',
      math: {
        mathjax: nodejs + 'MathJax/MathJax.js',
        config: 'TeX-AMS_HTML-full'
      },
      dependencies: [
        {
          src: revdir + 'lib/js/classList.js',
          condition: function() {
            return !document.body.classList;
          }
        }, {
          src: revdir + 'plugin/markdown/marked.js',
          condition: function() {
            return !!document.querySelector('[data-markdown]');
          }
        }, {
          src: revdir + 'plugin/markdown/markdown.js',
          condition: function() {
            return !!document.querySelector('[data-markdown]');
          }
        }, {
          src: revdir + 'plugin/highlight/highlight.js',
          condition: preCodeFn,
          async: true,
          callback: initHighFn
        }, {
          src: revdir + 'plugin/zoom-js/zoom.js',
          async: true
        }, {
          src: revdir + 'plugin/math/math.js',
          async: true
        }
      ]
    });
  };

  imgSrc = function() {
    var rep;
    rep = function() {
      var src1, src2;
      src1 = $(this).attr('src');
      src2 = src1.replace(/htm\/spark\/img/, 'img/spark');
      Util.log('src', src1, src2);
      $(this).attr('src', src2);
    };
    $('img').each(rep);
  };

  pdfCSS = function() {
    var link, nodejs, revdir;
    nodejs = '../../node_modules/';
    revdir = nodejs + 'reveal.js/';
    link = document.createElement('link');
    link.rel = 'stylesheet';
    link.type = 'text/css';
    link.href = window.location.search.match(/pdf/gi) ? revdir + 'css/print/pdf.css' : revdir + 'css/print/paper.css';
    document.getElementsByTagName('head')[0].appendChild(link);
  };

}).call(this);
