// Generated by CoffeeScript 1.10.0
(function() {
  var D3D, Stream;

  window.xUtil.fixTestGlobals();

  Stream = require('js/util/Stream');

  D3D = require('js/d3d/D3D');

  beforeAll(function() {
    var stream;
    stream = new Stream();
    return Util.noop(stream);
  });

  describe("d3d/Axes.coffee", function() {
    it("root        ", function() {
      return expect(true).toBe(true);
    });
    it("paths       ", function() {
      return expect(true).toBe(true);
    });
    return it("libs        ", function() {
      return expect(true).toBe(true);
    });
  });

}).call(this);
